export const ADD_CONTACT_REQUEST = "ADD_CONTACT_REQUEST"
export const ADD_CONTACT_SUCCESS = "ADD_CONTACT_SUCCESS"
export const ADD_CONTACT_FAIL = "ADD_CONTACT_FAIL"


export const GET_CONTACT_REQUEST = "GET_CONTACT_REQUEST"
export const GET_CONTACT_SUCCESS = "GET_CONTACT_SUCCESS"
export const GET_CONTACT_FAIL = "GET_CONTACT_FAIL"


export const GET_CONTACT_UPDATE_REQUEST = "GET_CONTACT_UPDATE_REQUEST"
export const GET_CONTACT_UPDATE_SUCCESS = "GET_CONTACT_UPDATE_SUCCESS"
export const GET_CONTACT_UPDATE_FAIL = "GET_CONTACT_UPDATE_FAIL"


export const DELETE_CONTACT_REQUEST = "DELETE_CONTACT_REQUEST"
export const DELETE_CONTACT_FAIL = "DELETE_CONTACT_FAIL   "
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS"