export const USER__REGISTER_REQUEST = "USER__REGISTER_REQUEST"
export const USER__REGISTER = "USER__REGISTER"
export const USER__REGISTER_FAIL = "USER__REGISTER_FAIL"


export const GET_ALL_USER_REGESTER = "GET_ALL_USER_REGESTER"
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS"
export const GET_ALL_USER_FAIL = "GET_ALL_USER_FAIL"


export const USER_LOGIN_REGESTER = " USER_LOGIN_REGESTER"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAI"



export const USER_LOGOUT = "USER_LOGOUT"





